//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCatalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materii
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materii()
        {
            this.NoteStudentis = new HashSet<NoteStudenti>();
            this.ProfesoriMateriis = new HashSet<ProfesoriMaterii>();
        }
    
        public int IdMaterie { get; set; }
        public string NumeMaterie { get; set; }
        public int An { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoteStudenti> NoteStudentis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfesoriMaterii> ProfesoriMateriis { get; set; }
    }
}
