//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCatalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteStudenti
    {
        public int IdNota { get; set; }
        public Nullable<double> Nota { get; set; }
        public Nullable<int> IdStudent { get; set; }
        public Nullable<int> IdProfesor { get; set; }
        public Nullable<int> IdMaterie { get; set; }
    
        public virtual Materii Materii { get; set; }
        public virtual Profesori Profesori { get; set; }
        public virtual Studenti Studenti { get; set; }
    }
}
